## Nama : Muhammad Nanda Arjuna Fadhillah
## NIM  : 2109106028
## Informatika A1 2021
## POSTTEST 7 TensorFlow

# Import Library

In [1]:
import tensorflow as tf
import numpy as np

# 1. Membuat TensorFlow dengan shape (5,5) dan nilai random dalam variabel random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1)
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

In [3]:
list_utt = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[-2.0965335e-01, -1.3993976e+00, -5.4795647e-01,  8.7259400e-01,
          3.3248085e-01],
        [-4.7624734e-01,  7.5609368e-01, -9.4994910e-02,  6.5820724e-01,
          2.5793374e-01],
        [ 2.0038645e+00, -6.9562840e-01, -6.6910112e-01, -9.4291139e-01,
         -2.6963162e-03],
        [-2.4351557e-01, -3.2541880e-01, -3.6375967e-01,  5.8542204e-01,
          1.1280807e+00],
        [-6.8968707e-01,  3.9414167e-01,  8.7205845e-01,  1.1976978e-01,
         -5.5206841e-01]],

       [[-2.5949800e-01,  1.0613734e+00,  1.0012702e+00, -6.1345887e-01,
          3.3055153e-01],
        [ 8.9762455e-01, -6.2647337e-01,  8.9826739e-01, -1.1285205e-01,
          1.0374856e+00],
        [-2.9208648e-01, -3.6934403e-01,  9.0961762e-02, -5.5928111e-01,
         -6.3088304e-01],
        [-1.0631151e-01, -1.9132267e-01, -3.6074585e-01,  2.0197911e+00,
          1.2849726e-01],
        [ 1.0442848e-01,  2.2906350e-01,  8.6999351e-01, -5.1898938e-01,
         -1.6735966e+00]],

      

In [5]:
slicing[2,2,2]
slicing[2]
tf.gather(slicing, indices=[2,2,2]).numpy()

array([[[-0.8202157 ,  0.22746041,  0.16679125,  2.2971537 ,
          0.5462674 ],
        [-2.1360257 ,  0.35455003, -0.95423883, -1.7773317 ,
         -0.2748292 ],
        [-1.096748  , -0.521841  , -0.80344456,  1.2661488 ,
          0.13929065],
        [-0.39554086, -0.6616406 , -1.0369576 ,  0.1615266 ,
         -0.0123045 ],
        [-1.8575132 , -0.4886678 ,  0.8082345 , -0.05603261,
          1.2941664 ]],

       [[-0.8202157 ,  0.22746041,  0.16679125,  2.2971537 ,
          0.5462674 ],
        [-2.1360257 ,  0.35455003, -0.95423883, -1.7773317 ,
         -0.2748292 ],
        [-1.096748  , -0.521841  , -0.80344456,  1.2661488 ,
          0.13929065],
        [-0.39554086, -0.6616406 , -1.0369576 ,  0.1615266 ,
         -0.0123045 ],
        [-1.8575132 , -0.4886678 ,  0.8082345 , -0.05603261,
          1.2941664 ]],

       [[-0.8202157 ,  0.22746041,  0.16679125,  2.2971537 ,
          0.5462674 ],
        [-2.1360257 ,  0.35455003, -0.95423883, -1.7773317 ,
         -0

In [6]:
tf.gather_nd(slicing, indices=[[0,2],[1,2],[2,2],[3,2],[4,2]]).numpy()

array([[ 2.0038645 , -0.6956284 , -0.6691011 , -0.9429114 , -0.00269632],
       [-0.29208648, -0.36934403,  0.09096176, -0.5592811 , -0.63088304],
       [-1.096748  , -0.521841  , -0.80344456,  1.2661488 ,  0.13929065],
       [-2.3320553 , -0.57130176,  0.14751619,  0.15430132, -0.25555378],
       [ 1.6070207 , -0.63930684,  0.04419544,  0.2856435 ,  1.0821941 ]],
      dtype=float32)

In [7]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([-0.6691011 ,  0.09096176, -0.80344456,  0.14751619,  0.04419544],
      dtype=float32)

# 2. Membuat Sebuah Tensor dengan shape(5,5) dari sebuah list dengan bilangan prima dalam variabel prime_tensor

In [9]:
list_prime = [[11, 13, 5, 7, 17],[23, 27, 29, 33, 39],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[11., 13.,  5.,  7., 17.],
       [23., 27., 29., 33., 39.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

# 3. Menampilkan DImensi dari Variabel

In [10]:
random_tensor.shape

TensorShape([5, 5])

In [11]:
prime_tensor.shape

TensorShape([5, 5])

# 4. Menampilkan Hasil Aritmatika 2 Variabel dengan 5 Operator

In [12]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("6. FloorDiv :",tf.math.floordiv(prime_tensor,random_tensor))
print("7. FloorMod :",tf.math.floormod(prime_tensor,random_tensor))
print("8. Greater :",tf.math.greater(prime_tensor,random_tensor))
print("9. Setara :",tf.equal(prime_tensor,random_tensor))
print("10. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("11. Greater Equal :",tf.math.greater_equal(prime_tensor,random_tensor))
print("12. Less :",tf.math.less(prime_tensor,random_tensor))
print("13. Less Equal :",tf.math.less_equal(prime_tensor,random_tensor))
print("14. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("15. Minimum :",tf.math.minimum(prime_tensor,random_tensor))
print("16. Kuadrat Perbedaan :",tf.math.squared_difference(prime_tensor,random_tensor))
print("17. TrueDiv :",tf.math.truediv(prime_tensor,random_tensor))
print("18. XdivY :",tf.math.xdivy(prime_tensor,random_tensor))
print("19. Xlog1pY :",tf.math.xlog1py(prime_tensor,random_tensor))
print("20. XlogY :",tf.math.xlogy(prime_tensor,random_tensor))
print("21. Atan2 :",tf.math.atan2(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[10.188682  14.484599   5.0653296  4.557296  17.099249 ]
 [23.591225  27.592823  26.877071  32.277103  38.94373  ]
 [31.643545  36.735676  42.856632  43.56784   46.617165 ]
 [51.514656  60.261772  60.974693  70.73537   74.532814 ]
 [77.25702   82.5621    88.43399   97.32067    2.132831 ]], shape=(5, 5), dtype=float32)
2. Pengurangan : tf.Tensor(
[[11.811318   11.515401    4.9346704   9.442704   16.900751  ]
 [22.408775   26.407177   31.122929   33.722897   39.05627   ]
 [30.356455   37.264324   39.143368   42.43216    47.382835  ]
 [54.485344   57.738228   61.025307   71.26463    71.467186  ]
 [80.74298    83.4379     89.56601    96.67933    -0.13283098]], shape=(5, 5), dtype=float32)
3. Perkalian : tf.Tensor(
[[  -8.9245       19.299784      0.32664686  -17.09893       1.6872228 ]
 [  13.598159     16.00622     -61.564957    -23.855608     -2.1945448 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496     

# 5. Menampilkan Nilai Maksimum dan Minimum dari Variabel random_tensor

In [20]:
maxb = tf.argmax(random_tensor, axis=0).numpy()
print ("Maksimum baris random tensor : ",maxb)
maxb

Maksimum baris random tensor :  [2 0 2 2 3]


array([2, 0, 2, 2, 3], dtype=int64)

In [21]:
maxk = tf.argmax(random_tensor, axis=1).numpy()
print ("Maksimum kolom random tensor : ",maxk)
maxk

Maksimum kolom random tensor :  [1 1 2 4 4]


array([1, 1, 2, 4, 4], dtype=int64)

In [22]:
minb = tf.argmin(random_tensor, axis=0).numpy()
print ("Minimum baris random tensor : ",minb)
minb

Minimum baris random tensor :  [4 4 1 0 2]


array([4, 4, 1, 0, 2], dtype=int64)

In [23]:
mink = tf.argmin(random_tensor, axis=1).numpy()
print ("Minimum kolom random tensor : ",mink)
mink

Minimum kolom random tensor :  [3 2 4 0 0]


array([3, 2, 4, 0, 0], dtype=int64)

# 6. Menampilkan Hasil dari Penggabungan Variabel random_tensor dengan prime_tensor(concatenation)

## Penggabungan Baris

In [24]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 1.1000000e+01,  1.3000000e+01,  5.0000000e+00,  7.0000000e+00,
         1.7000000e+01],
       [ 2.3000000e+01,  2.7000000e+01,  2.9000000e+01,  3.3000000e+01,
         3.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0000000e+00]], dtype=float32)

## Penggabungan Kolom

In [25]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  1.1000000e+01,  1.3000000e+01,  5.0000000e+00,
         7.0000000e+00,  1.7000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  2.3000000e+01,  2.7000000e+01,  2.9000000e+01,
         3.3000000e+01,  3.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0000000e+00]], dtype=float32)

# 7. Menampilkan Hasil Sorting dari Kedua Variabel Secara Descending


In [26]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 1.4845988 ,  0.0992484 ,  0.06532937, -0.8113182 , -2.4427042 ],
       [ 0.59282297,  0.5912243 , -0.05627038, -0.72289723, -2.1229296 ],
       [ 1.8566332 ,  0.6435448 ,  0.5678417 , -0.26432407, -0.3828359 ],
       [ 1.5328138 ,  1.2617711 , -0.02530608, -0.2646297 , -1.4853433 ],
       [ 1.132831  ,  0.32066926, -0.43789294, -0.56601   , -1.7429771 ]],
      dtype=float32)

In [27]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [28]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[17., 13., 11.,  7.,  5.],
       [39., 33., 29., 27., 23.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [29]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 1, 0, 3, 2],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])